spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test2?createDatabaseIfNotExist=true
    username: test2
    password: test2

  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        #        show_sql: true
        format_sql: true

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace
